# Versión de la sintaxis de Docker Compose
version: '3.8'

# Definición de los servicios (contenedores) que componen tu aplicación
services:
  # Servicio para tu Web API
  webapi:
    image: ghcr.io/luquitas234/academianovit2025:latest
    ports:
      - "8080:80"
    environment:
      - ASPNETCORE_URLS=http://+:80
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=db;Port=5432;Database=datos;Username=admin;Password=tivon1234
    restart: always
    container_name: academianovit_webapi
    depends_on:
      - db

  # Servicio para la base de datos PostgreSQL
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: datos
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: tivon1234
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    restart: always
    container_name: academianovit_db

  # ---------------------------------------------
  # Servicios de Monitoreo
  # ---------------------------------------------
  nodeexporter:
    image: prom/node-exporter:latest
    container_name: nodeexporter
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/host/rootfs:ro
    command:
      - '--path.proc=/host/proc'
      - '--path.sys=/host/sys'
      - '--collector.filesystem.mount-points-exclude=^/(dev|proc|sys|var/lib/docker/.+|var/lib/kubelet/pods/.+)($$|/)'
    restart: always
    network_mode: host

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    container_name: cadvisor
    volumes:
      - /:/root:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    restart: always
    privileged: true
    depends_on:
      - nodeexporter

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    restart: always
    depends_on:
      - nodeexporter
      - cadvisor

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
    restart: always
    depends_on:
      - prometheus

# Definición de volúmenes para persistencia de datos
volumes:
  db_data:
  prometheus_data:
  grafana_data:
