# my global config
global:
  scrape_interval: 15s # Establece el intervalo de scrapeo por defecto en 15 segundos.
  evaluation_interval: 15s # Evalúa las reglas cada 15 segundos.

# Ascrape configuration for prometheus
scrape_configs:
  # Job para el propio Prometheus
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Job para Node Exporter (métricas del sistema host)
  - job_name: 'node_exporter'
    static_configs:
      - targets: ['localhost:9100']

  # Job para cAdvisor (métricas de contenedores)
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']

  # Job para  Web API (con 5 réplicas)
  - job_name: 'academianovit_webapi'
    static_configs:
      - targets: ['cadvisor:8080']
