# Configuración global de Prometheus
global:
  scrape_interval: 15s # Intervalo de tiempo para recolectar métricas

# Configuración de los trabajos de recolección (scrape jobs)
scrape_configs:
  # Trabajo para recolectar métricas de Node Exporter (del host)
  - job_name: 'node-exporter'
    # Node Exporter se ejecuta en modo host, por lo que lo scrapeamos en localhost
    static_configs:
      - targets: ['localhost:9100']

  # Trabajo para recolectar métricas de cAdvisor (de los contenedores)
  - job_name: 'cadvisor'
    # cAdvisor se ejecuta como un servicio Docker, Prometheus lo accede por el nombre del servicio
    static_configs:
      - targets: ['cadvisor:8080']

  # Trabajo para recolectar métricas de Prometheus (automonitoreo)
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
