# Nombre del workflow, aparecerá en la interfaz de GitHub Actions
name: Build & Push Docker Image to GHCR (DEV)

# Evento que dispara el workflow
# Se ejecutará cada vez que se haga un 'push' a la rama 'development'
on:
  push:
    branches:
      - development # Asegura que este workflow solo se ejecute para la rama 'development'

# Definición de variables de entorno para el workflow
env:
  # Nombre completo del repositorio en minúsculas para usar en las etiquetas de la imagen
  # Esto será "luquitas234/academianovit2025"
  REPO_NAME_LOWER: luquitas234/academianovit2025 # Ajusta esto según tu repositorio real 
  # Ruta al directorio que contiene el Dockerfile (relativa a la raíz del repositorio)
  DOCKERFILE_CONTEXT: Dockerfile # Ajusta esto si tu Dockerfile no está en la raíz del proyecto Web API

# Definición de los trabajos (jobs)
jobs:
  build_and_push_image:
    runs-on: ubuntu-24.04 # Especifica la versión de Ubuntu que deseas usar
    permissions:
      contents: read
      packages: write # Permiso necesario para escribir en GitHub Container Registry

    steps:
      # Paso 1: Checkout del repositorio
      - name: Checkout del repositorio
        uses: actions/checkout@v4

      # Paso 2: Configurar Docker Buildx
      - name: Configurar Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Paso 3: Login en GitHub Container Registry (GHCR)
      - name: Login en GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Paso 4: Construir y Pushear la imagen Docker
      - name: Construir y Pushear imagen Docker
        uses: docker/build-push-action@v5
        with:
          context: ${{ env.DOCKERFILE_CONTEXT }}
          push: true
          
          tags: |
            ghcr.io/${{ env.REPO_NAME_LOWER }}:latest
            ghcr.io/${{ env.REPO_NAME_LOWER }}:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
